### PR TITLE
No restart loops on init

### LINKED ISSUE #667: systemd auto-restart causing more problems than it solves
Have had a few folks on Ubuntu reporting that `tpm2-abrmd` gets installed even though the platform doesn't have a TPM device (no /dev/tpm*).

- https://github.com/tpm2-software/tpm2-abrmd/issues/661
- https://github.com/tpm2-software/tpm2-tss/issues/1541
- https://www.reddit.com/r/linuxquestions/comments/dhinl0/what_is_tpm2abrmdservice_and_why_does_it_try_fail/

The systemd config we use will attempt to auto-restart the daemon if it dies but without a TPM device the daemon keeps dying and systemd keeps restarting it. This spams the hell out of users lots. The preferable approach would be to figure out a way to let systemd know when a failure is unrecoverable. Baring this I think the only viable solution would be to stop auto-restarting the daemon. Alternatively we could modify the daemon such that it will run even if there's no TPM device. It could instead run normally but return errors to users indicating that no TPM device is available.

### PR DESCRIPTION
**Pull request by flihp**
This PR resolves #667 using the general approach described in the thread. After implementing this with what look like the most appropriate exit codes from `sysexit.h`, it's seems as though we could simplify this by using a single exit code. This is because none of the error cases in the init thread appear to be recoverable by restarting the daemon. This  is definitely true for TCTI failures (the whole reason for #667), but may not be the case for things like failures in registering signal handlers and starting threads. If you have opinions about this please include them here.

There's some additional clean-up here too since the `TctiFactory` object has become dead weight now that we're using libtss2-tctildr. It got in the way here so now it's gone.

### CODE REVIEW

**Comment by flihp** [comment]
This works fine for the error codes identified but there's an additional case that we may want to cover: dbus permissions. Specifically the call to "own" the name `com.intel.tss2.Tabrmd` will fail if the required dbus policy hasn't been installed properly. This would only happen on a seriously misconfigured system but that logic applies to the situations fixed in this PR so might as well cover this case too?

**Comment by martinezjavier** [comment]
@flihp we also got a [bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1769215) in Fedora about the restart loop when there's no TPM chardev. And while cherry-picking the commits in this PR would solve the issue I wonder if we want systemd to restart the `tpm2-abrmd` at all.

My rationale is that the service is D-Bus activated anyways. So if the daemon can't be restarted due an unrecoverable condition, there's no point to attempt to do it. And if it can be started, then it will be when a client does a D-Bus call.

Also, there's a [ConditionPathExistsGlob=](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#ConditionPathExistsGlob=) option for the systemd service `[Unit]` section, that can be used to check if a TPM chardev exists and don't even attempt to start the service if that's not the case.

I think we should do both changes for the service file, something like the following:

```
diff --git dist/tpm2-abrmd.service.in dist/tpm2-abrmd.service.in
index dba5c356ebc..43450a692e5 100644
--- dist/tpm2-abrmd.service.in
+++ dist/tpm2-abrmd.service.in
@@ -1,12 +1,9 @@
 [Unit]
 Description=TPM2 Access Broker and Resource Management Daemon
+ConditionPathExistsGlob=/dev/tpm*
 
 [Service]
 Type=dbus
-Restart=always
-# 69=EX_UNAVAILABLE, 71=EX_OSERR, 74=EX_IOERR
-RestartPreventExitStatus=69 71 74
-RestartSec=5
 BusName=com.intel.tss2.Tabrmd
 StandardOutput=syslog
 ExecStart=@SBINDIR@/tpm2-abrmd
```

What do you think about this? I didn't propose a pull-request because I wanted to know your opinion first.

The `ConditionPathExistsGlob=/dev/tpm*` probably should be behind a `configure` option, so users that want to use the `tpm2-abrmd` with the TCP mssim don't need to edit the service file. But probably would make sense for distros to enable this check.

**Comment by martinezjavier** [comment]
> The `ConditionPathExistsGlob=/dev/tpm*` probably should be behind a `configure` option

On a second thought we don't really need to have this under a configure option. Since a user that wants to run the `tpm2-abrmd` with the mssim TCTI will need to modify the `ExecStart=` option anyways.

So adding a comment explaining that the `ConditionPathExistsGlob=/dev/tpm*` needs to be commented out if the mssim TCTI will be used.

**Comment by flihp** [comment]
I agree. While hacking up this patch it became apparent that none of these failures are recoverable. Thus I agree that restarting makes little sense. I set the `Restart=always` stuff up back when the daemon still had a few crashes I hadn't worked out yet (~2 years ago) and never revisited it. The pointer to `ConditionPathExistsGlob` is super helpful.

I'll roll this into a new issue to keep it visible and organized.

**Pull request merged**
