### PR TITLE
tests: run without X

### PR DESCRIPTION
**Pull request by alonbl**
Solves:

$ DISPLAY= make check

FAIL: test/tss2-tcti-tabrmd_unit

** (process:17633): CRITICAL **: 23:53:22.403: failed to allocate dbus proxy object:
Error spawning command line ?dbus-launch --autolaunch=4f9189e347d5cdf343

Signed-off-by: Alon Bar-Lev <alon.barlev@gmail.com>

### CODE REVIEW

**Comment by flihp** [comment]
Hi @alonbl. Thanks for the patch. It looks like an change in the upstream tpm2-tss build is now causing a failure in the CI for this project and the changes you've made in 812606e  are relevant. I do however need a 'signed-off-by' line from you on the commit before I can merge it. This requirement is easy to miss in our CONTRIBUTING.md since it's the last bullet in a list of requirements: https://github.com/tpm2-software/tpm2-abrmd/blob/master/CONTRIBUTING.md#patch-requirements. We'll be setting up the dco bot from probot to automate this check in the future but for now it's still a manual check.

**Comment by alonbl** [comment]
Hi @flihp, I added signed-off for the m4 commit.

**Comment by flihp** [comment]
Thanks for the quick turn around on this @alonbl. I'll apologize in advance for this but I've gone ahead and hacked this PR up a bit to extract the bits relevant to fixing the CI failures caused by upstream changes in tpm2-tss as well as the aclocal changes (for consistency). See #579.

I'd like to leave 3c7f415 for after the 2.1.0 release is tagged. Rebasing this same branch on master now that #579 has been merged should just cause 0408d22 to be dropped so hopefully I haven't made too much extra work for you.

**Comment by alonbl** [comment]
Done... had you use gerrit instead of github this would have much easier :)

**Comment by alonbl** [comment]
On Wed, Jan 23, 2019 at 1:31 PM Jonas Witschel <notifications@github.com>
wrote:

> I have been successfully using dbus-run-session for a while now when
> building the AUR package tpm2-abrmd-git
> <https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tpm2-abrmd-git#n42>
> for Arch Linux.
>
Yes, me too...

**Comment by flihp** [comment]
Thx for the data here. Will take a look @ `dbus-run-session` once the 2.1.0 release is done.

**Comment by alonbl** [comment]
Hi,
This is a fix to allow tests to succeed, it was reported by users of us[1], please include this in the version so I won't be required to patch and run autoreconf.
Thanks!

[1] https://bugs.gentoo.org/show_bug.cgi?id=675738

**Comment by flihp** [comment]
Merging now. Will roll another RC as well to get this into next release.

**Pull request merged**
