### PR TITLE
Document configure flags better. Fixes #336

### LINKED ISSUE #336: Document configure flags better
Add configure flags to override:
*  /usr/local/etc/default
     This flag will be --with-sysdefaultdir.  E.g., $ configure --with-sysdefaultdir=/etc/default

* /usr/local/share/dbus-1/system-services
     This flag will be --with-dbusdatadir.  E.g., 
     $ configure --with-dbusdatadir=/usr/share/dbus-1/system-services

Update INSTALL.md with the new flags.  Also add these clarifications:
* Change version of IBM TPM2 simulator from 532 to 974.
* Mention default values for GNU installation directories at:
https://www.gnu.org/prep/standards/html_node/Directory-Variables.html
* Add missing example:
	--with-systemdpresetdir=/lib/systemd/system-preset
* Add missing dependency on D-Bus 1 libraries
* Typo: s/overriden/overridden/

### PR DESCRIPTION
**Pull request by dantpm**
Fix configure documentation problems in INSTALL.md.
This includes 
updating IBM simulator location, 
adding link to GIT configure defaults, 
dding example for --with-systemdpresetdir, 
documenting use of --sysconfdir and --datarootdir and
removing unused EnvironmentFile option in tpm2-abrmd.service
Address review comments in #337.
Fixes #336.

### CODE REVIEW

**Comment by dantpm** [comment]
I removed the environment filename from the configuration due to review comments here:
https://github.com/tpm2-software/tpm2-abrmd/pull/337 (follow this link for a fuller discussion)

> martinezjavier 4 days ago  Member
> Is this even installed? I also think this line could just be removed from the systemd unit file.

What I wanted to do was add a --with-sysdefaultdir option to specify where the EnvironmentFile is located.

You opened another ticket, #339, to look into this further.

So, we can either remove the unused EnvironmentFile line or document how to configure the value of the (currently) non-existent file in the INSTALL.md file.  Which is your preference?

**Comment by martinezjavier** [comment]
> I removed the environment filename from the configuration due to review comments here:

@dantpm I think what @flihp meant is that you should document in the commit message why you are removing it. Otherwise people have not way to know it, unless they dig for discussions on closed issues on Github.

Related, please make sure that your commits format (subject line, commit message, etc) conform to what's described in https://github.com/tpm2-software/tpm2-abrmd/blob/master/CONTRIBUTING.md.

For example, you are not providing a commit message and Signed-off-by tag.

**Comment by dantpm** [comment]
OK.  The reason the EnvironmentFile line is being removed is because it is not installed and not used. It is also not configurable.
(I can add this to the commit message, but that is limited to 80 characters).

**Comment by martinezjavier** [comment]
> (I can add this to the commit message, but that is limited to 80 characters).

The 80 char limit is just per line, you could have as many lines as you want. The more, the merrier :smiley:

**Comment by dantpm** [comment]
**Document how to add to permitted abrmd users and maybe how to change default user, tss #349**
I added this new bug on adding permitted abrmd users.  We may also consider adding configure and other code to change the default user (tss) to something else, but I am afraid TPM has enough over-engineering :-).

**Comment by dantpm** [comment]
OK, I'll add a multiple commit messages (multiple git commit -m)

**Comment by dantpm** [comment]
I tried git rebase and git push but it does not work (see script below).  That is the commit message is not updated. 

What's the missing step?

I can easily delete this pull request and create a new one, but that does not seem preferred. 
But updating an existing pull request does not work.

SCRIPT OUTPUT (sorry git does something weird with the formatting!):

dano@tumalo:~/tpm/git/tpm2-abrmd-dan-diroptions$ git rebase -i origin/master
# Rebase 84e9e9a..1f87402 onto 84e9e9a (1 command(s))
#
# Commands:
# p, pick = use commit
# r, reword = use commit, but edit the commit message
# e, edit = use commit, but stop for amending
# s, squash = use commit, but meld into previous commit
# f, fixup = like "squash", but discard this commit's log message
# x, exec = run command (the rest of the line) using shell
# d, drop = remove commit
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out

dano@tumalo:~/tpm/git/tpm2-abrmd-dan-diroptions$
dano@tumalo:~/tpm/git/tpm2-abrmd-dan-diroptions$ git push -f
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Username for 'https://github.com': dantpm
Password for 'https://dantpm@github.com':
Everything up-to-date

**Comment by martinezjavier** [comment]
@dantpm two things, first could you please enclose commands into a pair of ```

Otherwise the Github web UI does weird things with the text format and it's very hard to read.

Second, I think it's doing the right thing. When you execute rebase -i origin/master, then $EDITOR should open something like the following:

```
pick 241f3ccb0601 INSTALL.md: Fix some text about foobar
fixup 69580384aefe fixup! INSTALL.md: Fix some text about foobar

# Rebase fb9bc17130c6..241f3ccb0601 onto fb9bc17130c6 (1 command)
#
# Commands:
# p, pick = use commit
# r, reword = use commit, but edit the commit message
# e, edit = use commit, but stop for amending
# s, squash = use commit, but meld into previous commit
# f, fixup = like "squash", but discard this commit's log message
# x, exec = run command (the rest of the line) using shell
# d, drop = remove commit
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
```

What this says is that you have N commits on top of your rebase base commit (origin/master). In my example there are two commits with sha-1 241f3ccb0601 and 69580384aefe.

For the first commit I chose `pick` since I want that commit to be picked, and for the second `fixup` since is a fixup for the first commit. So basically what you do is take the first one, squash the second and give me a single commit.

This could be achieved just with `git commit -a --amend` but it's an example so you get the grasp of `git rebase -i`.

**Comment by martinezjavier** [comment]
@dantpm about the git push, you need to provide a remote and a branch, i.e:

```
$ git push -f origin my-branch-with-fixes
```

Unless you have a default remote, as the command says in your example.

**Comment by dantpm** [comment]
Thanks for the tips--I'll try them.  It is funny that git doesn't use the branch specified in "git checkout". I assume it defaults to the "master" branch, not the current branch specified to "git checkout". If that's the case, it would explain some or all the problems.

**Comment by martinezjavier** [comment]
@dantpm I think it does at a certain state, IIRC your branch name should match the name of the remote branch you used to checkout. So for example git push -f will work if your branch is called master and you checkout out from origin/master.

Now, it won't really work unless you have access to the origin repository, but you want to push to a different remote and send a pull request.

**Comment by dantpm** [comment]
The problem is the fixup line does not appear. And my commit does not appear at all in the text editor. This is even though the commit is there (changes already committed)!
And the commit shows up with a "git show" command.

I believe I have to change all the other "pick" lines to "squash" to merge the change.  Correct?

**Comment by martinezjavier** [comment]
@dantpm There's something wrong with your branch for sure. Please look at my other comment in https://github.com/tpm2-software/tpm2-tss/pull/792.

In general, I think you should use `git rebase origin/master` instead of `git merge origin/master`. And always use as a base of your work the branch you are targeting to.

**Comment by martinezjavier** [comment]
I don't see what's wrong with this particular branch though, but if the commits are not showing into the `git rebase -i` editor, then something isn't right.

**Comment by dantpm** [comment]
I was able to merge the multiple commits using the trick from @martinezjavier of creating a new branch and "git cherry-pick" from the old branch with multiple commits.

So this should be all ready to pull.

**Comment by dantpm** [comment]
I split this pull request into two, as requested
Issue #342 for *.c code changes
Issue #356 for INSTALL.md changes

**Pull request closed without merging**
